{% comment %} apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: chatbot-ai
data:
  # This points directly to the first pod of the Kafka StatefulSet
  KAFKA_BOOTSTRAP: "kafka-0.kafka.chatbot-ai.svc.cluster.local:9092"
  REDIS_HOST: "redis"
  QDRANT_HOST: "qdrant" {% endcomment %}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.appConfig }}
data:
  # Dynamically constructed to match your release name and namespace
  KAFKA_BOOTSTRAP: "{{ include "chatbot-ai.fullname" . }}-kafka-0.{{ include "chatbot-ai.fullname" . }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
  REDIS_HOST: "{{ include "chatbot-ai.fullname" . }}-redis"
  QDRANT_HOST: "{{ include "chatbot-ai.fullname" . }}-qdrant"
