apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.appConfig }}
data:
  # Dynamically constructed to match your release name and namespace
  KAFKA_BOOTSTRAP: "{{ include "chatbot-ai.fullname" . }}-kafka-0.{{ include "chatbot-ai.fullname" . }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
  REDIS_HOST: "{{ include "chatbot-ai.fullname" . }}-redis"
  QDRANT_HOST: "{{ include "chatbot-ai.fullname" . }}-qdrant"
