apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
spec:
  accessModes:
    {{- toYaml .Values.storage.qdrant.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.qdrant.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  accessModes:
    {{- toYaml .Values.storage.kafka.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.kafka.size }}
