apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbot-ai.fullname" . }}-worker
  labels:
    app: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      dnsPolicy: {{ .Values.dns.policy | quote }}
      dnsConfig:
        nameservers:
          {{- toYaml .Values.dns.nameservers | nindent 10 }}
        searches:
          {{- toYaml .Values.dns.searches | nindent 10 }}
        options:
          - name: ndots
            value: "5"
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: {{ .Values.worker.command | toJson }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "ps aux | grep 'snowflake_consumer' | grep -v grep"]
            initialDelaySeconds: {{ .Values.worker.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.probes.liveness.periodSeconds }}
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.snowflake }}
            - configMapRef:
                name: {{ .Values.configMaps.appConfig }}
