FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc curl && rm -rf /var/lib/apt/lists/*

# Look for requirements in the parent folder (root)
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything from the root into /app
COPY . /app/

CMD ["uvicorn", "services.api_gateway.main:app", "--host", "0.0.0.0", "--port", "8000"]
