apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbot-ai.fullname" . }}-api
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      dnsPolicy: {{ .Values.dns.policy | quote }}
      dnsConfig:
        nameservers:
          {{- toYaml .Values.dns.nameservers | nindent 10 }}
        searches:
          {{- toYaml .Values.dns.searches | nindent 10 }}
        options:
          - name: ndots
            value: "5"

      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000

          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}

          envFrom:
            - secretRef:
                name: app-secrets
            - secretRef:
                name: {{ .Values.secrets.snowflake }}
            - configMapRef:
                name: {{ .Values.configMaps.appConfig }}