apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chatbot-ai.fullname" . }}-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - testing-chatbot.duckdns.org
      secretName: tls-secret

  rules:
    - host: testing-chatbot.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chatbot-ai.fullname" . }}-api
                port:
                  number: 80